
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v3

#        - name: Chocolatey Action
#          uses: crazy-max/ghaction-chocolatey@v2.1.0
#          with:
#            args: -h

#        - name: Install ffmpeg?
#          run: npm install ffmpeg-static

#        - name: Install FFMPEG?
#          run: choco install ffmpeg -y --no-progress

        - name: download it i guess
          shell: pwsh
          run: Invoke-WebRequest -Uri https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z -OutFile ffmpeg.7z

        - name: IS IT HERE?
          run: ls

        - name: fuck it we extract
          run: 7z e ffmpeg.7z -oFFXIVVoiceClipNameGuesser/bin/Release/res ffmpeg.exe -r

        - name: IS IT IN THERE
          run: ls ./FFXIVVoiceClipNameGuesser/bin/Release/res


# 7z e ffmpeg.7z -offmpeg ffmpeg.exe -r

# GOOD
#        - name: Install msbuild
#          uses: microsoft/setup-msbuild@v1.1

# GOOD
#        - name: Build app
#          run: msbuild FFXIVVoiceClipNameGuesser\FFXIVVoicePackCreator.csproj -p:Configuration=Release

#        - name: Is stuff here?
#          run: ls
          #run: cd FFXIVVoiceClipNameGuesser\bin\Release && dir

# Download FFMPEG to res
#        - name: Download FFMPEG
#          run: 
# Extract
# RM other stuff maybe
# Zip back up
# upload

